### ISSUE TITLE
vscode使用uniapp项目实时调试微信小程序

### ISSUE THREAD

**Issue by 0x7A7A6572** [0x7A7A6572/MessageBoard#10]
https://zzerx.cn/2022/06/29/vscode%E4%BD%BF%E7%94%A8uniapp%E9%A1%B9%E7%9B%AE%E5%AE%9E%E6%97%B6%E8%B0%83%E8%AF%95%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F/ 

 前言 整活 开发调试 注意事项   前言 在使用了一段时间的HbuilderX写uniapp之后，还是不太习惯HbuilderX，想着用回vscode编写uniapp项目，主要用uniapp写微信小程序。记录一下过程。  整活 使用Vue3&#x2F;Vite版 npx degit dcloudio

**Comment by 0x7A7A6572** [comment]
`npm run dev:mp-weixin` 过一段时间后会报以下错误，然后终止同步调试，经过重新运行命令才能继续，网上的说法时文件占用，但未能解决。 
```shell
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\zzerx\WORK\FruitStore\node_modules\rollup\dist\shared\index.js:4239:10)
    at ReaddirpStream.NodeFsHandler$1._boundHandleError (C:\Users\zzerx\WORK\FruitStore\node_modules\rollup\dist\shared\index.js:2715:43)
    at ReaddirpStream.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}
```
